<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MO-4G-BcchCfg</name>
   <tag></tag>
   <elementGuidId>d71b7e9d-f4a9-418d-a97c-862fa2e8b595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@aria-label='MO_4G_BcchCfg']//div[@role='checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
