<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>East-Amman-Option1-E</name>
   <tag></tag>
   <elementGuidId>6c7cccf5-f390-4846-9867-41b5e2cb2e59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@aria-label='301-ULT_King_Hussein_St_PD_Fiber_Manage_B22']//div[@role='checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
