<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>West-Amman-Option1-B</name>
   <tag></tag>
   <elementGuidId>7280a108-22b5-4109-b233-56b87fa7e3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@aria-label='201-UL_Jordan_Hospital_PF_DIBS_Manage_A2']//div[@role='checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
