<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>30-May</name>
   <tag></tag>
   <elementGuidId>53db5918-ebbd-45a0-8f76-615fa1d430ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/ngb-popover-window[1]/div[2]/p-calendar[1]/span[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[5]/td[6]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
