<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NextDate</name>
   <tag></tag>
   <elementGuidId>8512ce4a-6e9b-4c15-8252-e4f46433ea80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/ngb-modal-window/div/div/div/div[2]/div/p-calendar/span/div/div/div/div[2]/table/tbody/tr[2]/td[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
