<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Type-Arrow</name>
   <tag></tag>
   <elementGuidId>dcd31899-78cd-4b18-ba97-0f08873c7622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-son-report-type[1]/div[2]/app-select[1]/p-dropdown[1]/div[1]/div[1]/chevrondownicon[1]/*[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
